baseURL = "https://meantint.github.io/"
languageCode = "ko-kr"
defaultContentLanguage = "en-us"
theme = "meantint"
title = "Meantint's BLog"
description = "Hi"


googleAnalytics = "G-RBWB580JRH"
enableRobotsTXT = true
author = "Meantint"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# Use HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true