languageCode: "ko-kr"
defaultContentLanguage: "en-us"
baseUrl: "https://meantint.github.io"
title: "Meantint"
theme: "anubis"
paginate: 10
disqusShortname: Meantint
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: All Post
    title: All Post
    url: /post/
    weight: 0
  - identifier: Git
    name: Git
    title: Git
    url: /categories/git
    weight: 1
  - identifier: Programmers
    name: Programmers
    title: Programmers
    url: /categories/programmers
    weight: 1
  - identifier: BOJ
    name: BOJ
    title: BOJ
    url: /categories/boj
    weight: 1

params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown